<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\cache\CachePluginBase;

/**
 * Implements hook_views_post_render().
 */
function asocolderma_data_core_views_post_render(ViewExecutable $view, &$output, CachePluginBase $cache) {
  $actions_markup = [
    '#markup' => '<div style="padding:16px;background:#111;color:#fff;margin-top:16px;">TEST FOOTER - ' . $view->id() . ' / ' . $view->current_display . '</div>',
  ];

  $output['asocolderma_data_actions'] = $actions_markup;
}
