<?php

namespace Drupal\asocolderma_data_core\Controller;

/**
 * Exports asociados data and stores export logs.
 */
class AsociadosExportController extends DataExportBaseController
{

	/**
	 * {@inheritdoc}
	 */
	protected function getExportConfig(): array
	{
		return [
			'module_key' => 'asociados',
			'module_label' => 'asociados',
			'table_name' => 'asocolderma_import_asociados',
			'alias' => 'a',
			'filename_prefix' => 'asociados_export',
			'status_field' => 'estado_afiliacion',
			'numeric_fields' => [
				'valor_cuota_vigente',
			],
			'combine_fields' => [
				'id_asocolderma',
				'numero_documento',
				'primer_nombre',
				'segundo_nombre',
				'primer_apellido',
				'segundo_apellido',
				'correo_principal',
				'telefono_celular',
				'registro_medico_tarjeta',
				'ciudad_ejercicio',
				'departamento',
				'universidad_residencia',
				'especialidad',
				'tipo_asociado',
			],
			'columns' => [
				'id_asocolderma' => 'ID AsoColDerma',
				'estado_afiliacion' => 'Estado afiliación',
				'tipo_asociado' => 'Tipo asociado',
				'fecha_ingreso_asocolderma' => 'Fecha ingreso AsoColDerma',
				'edad' => 'Edad',
				'miembro_numero_1' => 'Miembro número 1',
				'miembro_numero_2' => 'Miembro número 2',
				'capitulo_regional' => 'Capítulo regional',
				'primer_nombre' => 'Primer nombre',
				'segundo_nombre' => 'Segundo nombre',
				'primer_apellido' => 'Primer apellido',
				'segundo_apellido' => 'Segundo apellido',
				'fecha_nacimiento' => 'Fecha nacimiento',
				'estado_civil' => 'Estado civil',
				'sexo' => 'Sexo',
				'tipo_documento' => 'Tipo documento',
				'numero_documento' => 'Número documento',
				'pais_nacimiento' => 'País nacimiento',
				'direccion_principal' => 'Dirección principal',
				'correspondencia_en' => 'Correspondencia en',
				'correo_principal' => 'Correo principal',
				'telefono_celular' => 'Teléfono celular',
				'registro_medico_tarjeta' => 'Registro médico / tarjeta',
				'pais_ejercicio' => 'País ejercicio',
				'ciudad_ejercicio' => 'Ciudad ejercicio',
				'departamento' => 'Departamento',
				'facultad_pregrado' => 'Facultad pregrado',
				'pais_pregrado' => 'País pregrado',
				'titulo_universitario' => 'Título universitario',
				'universidad_residencia' => 'Universidad residencia',
				'pais_residencia' => 'País residencia',
				'especialidad' => 'Especialidad',
				'subespecialidad' => 'Subespecialidad',
				'pertenece_filial' => 'Pertenece filial',
				'grupos_estudio' => 'Grupos de estudio',
				'recertificado_camec' => 'Recertificado CAMEC',
				'fecha_inicio_recertificacion' => 'Fecha inicio recertificación',
				'fecha_fin_recertificacion' => 'Fecha fin recertificación',
				'mostrar_perfil_publico' => 'Mostrar perfil público',
				'correo_publico' => 'Correo público',
				'sitio_web_publico' => 'Sitio web público',
				'horario_atencion' => 'Horario atención',
				'telefono_publico_1' => 'Teléfono público 1',
				'telefono_publico_2' => 'Teléfono público 2',
				'perfil_profesional' => 'Perfil profesional',
				'direccion_consultorio' => 'Dirección consultorio',
				'imagenes_consultorio' => 'Imágenes consultorio',
				'palabras_clave_tags' => 'Palabras clave',
				'capilaroscopia' => 'Capilaroscopia',
				'cicatrices_acne' => 'Cicatrices acné',
				'dermatologia_general' => 'Dermatología general',
				'dermatologia_oncologica' => 'Dermatología oncológica',
				'dermatologia_pediatrica' => 'Dermatología pediátrica',
				'dermatopatologia' => 'Dermatopatología',
				'fototerapia' => 'Fototerapia',
				'laser' => 'Láser',
				'microdermoabrasion' => 'Microdermoabrasión',
				'peeling' => 'Peeling',
				'inyectables' => 'Inyectables',
				'trasplante_pelo' => 'Trasplante pelo',
				'otros_servicios' => 'Otros servicios',
				'estado_cuota' => 'Estado cuota',
				'valor_cuota_vigente' => 'Valor cuota vigente',
				'fecha_ultimo_pago' => 'Fecha último pago',
				'comprobante_pago' => 'Comprobante pago',
				'carta_presentacion_1' => 'Carta presentación 1',
				'carta_presentacion_2' => 'Carta presentación 2',
				'copia_rut' => 'Copia RUT',
				'copia_cedula_id' => 'Copia cédula ID',
				'carta_solicitud_ingreso' => 'Carta solicitud ingreso',
				'hoja_vida' => 'Hoja de vida',
				'copia_diploma_medico' => 'Copia diploma médico',
				'copia_diploma_dermatologo' => 'Copia diploma dermatólogo',
				'registro_rethus' => 'Registro RETHUS',
				'carta_autorizacion_verificacion' => 'Carta autorización verificación',
				'certificacion_congreso_publicacion' => 'Certificación congreso/publicación',
				'otros_documentos_adjuntos' => 'Otros documentos adjuntos',
				'validation_status' => 'Estado validación',
				'created' => 'Fecha creación',
			],
			'labels' => [
				'combine' => 'Búsqueda general',
				'is_active' => 'Estado',
				'estado_afiliacion' => 'Estado',
				'validation_status' => 'Estado validación',
				'id_asocolderma' => 'ID AsoColDerma',
				'numero_documento' => 'Número documento',
				'primer_nombre' => 'Primer nombre',
				'segundo_nombre' => 'Segundo nombre',
				'primer_apellido' => 'Primer apellido',
				'segundo_apellido' => 'Segundo apellido',
				'correo_principal' => 'Correo principal',
				'telefono_celular' => 'Teléfono celular',
				'ciudad_ejercicio' => 'Ciudad ejercicio',
				'departamento' => 'Departamento',
				'universidad_residencia' => 'Universidad residencia',
				'especialidad' => 'Especialidad',
				'tipo_asociado' => 'Tipo asociado',
			],
		];
	}
}
